### Create order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "customer_name": "order 1",
  "items" : [
    "item 1",
    "item 2",
    "item 3"
  ],
  "amount": 100
}

### List orders
GET http://localhost:3000/orders HTTP/1.1

### List orders active orders
GET http://localhost:3000/orders?status=active HTTP/1.1

### Get order
GET http://localhost:3000/orders/a95117a0-dfb3-4e3c-ab14-993f127083ed HTTP/1.1

### Update order
PUT http://localhost:3000/orders/
Content-Type: application/json

{
  "id": "a95117a0-dfb3-4e3c-ab14-993f127083ed",
  "customer_name": "order 1 updated",
  "status": "complete",
  "items" : [
    "item 2",
    "item 3",
    "item 4"
  ],
  "amount": 200
}

### Delete order
DELETE http://localhost:3000/orders/a95117a0-dfb3-4e3c-ab14-993f127083ed HTTP/1.1