services:
  grpc:
    build:
      context: .
      target: grpc
  
  rest:
    build:
      context: .
      target: rest
    ports:
      - "3000:3000"
    depends_on:
      - grpc

  graphql:
    build:
      context: .
      target: graphql
    ports:
      - "8080:8080"
    depends_on:
      - grpc