// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateOrderRequest struct {
	CustomerName string   `json:"customerName"`
	Items        []string `json:"items"`
	Amount       int32    `json:"amount"`
}

type DeleteOrderRequest struct {
	ID string `json:"id"`
}

type Empty struct {
	Empty *bool `json:"empty,omitempty"`
}

type GetOrderRequest struct {
	ID string `json:"id"`
}

type ListOrdersRequest struct {
	CustomerName *string `json:"customerName,omitempty"`
	Status       *string `json:"status,omitempty"`
}

type Mutation struct {
}

type Order struct {
	ID           string   `json:"id"`
	CustomerName string   `json:"customerName"`
	Status       string   `json:"status"`
	Amount       int32    `json:"amount"`
	Items        []string `json:"items"`
}

type Query struct {
}

type UpdateOrderRequest struct {
	ID           string   `json:"id"`
	CustomerName string   `json:"customerName"`
	Status       string   `json:"status"`
	Amount       int32    `json:"amount"`
	Items        []string `json:"items"`
}
